language: ruby

services:
  - docker
  
script: 
  - docker build .  -t cookie_ds_demo
  # in CI we would only run light weight tests 
  - docker run -v"$PWD:/app/" cookie_ds_demo snakemake test -F
  - docker run -v"$PWD:/app/" cookie_ds_demo snakemake lint -F
  # in CD we would run the entire container default command here we use travis for both
  - docker run -v"$PWD:/app/" cookie_ds_demo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local-dir: docs
  on:
    branch: master