language: ruby

services:
  - docker
  
script: 
  - docker build .  -t cookie_ds_demo
  # in CI we would only run light weight tests 
  - docker run -v"$PWD:/app/" cookie_ds_demo snakemake test -F && snakemake lint -F
  # in CD we would run the entire container default command here we use travis for both
  - docker run -v"$PWD:/app/" cookie_ds_demo
