version: '3.7'
services:
  build_image:
    build: ./docker/
    image: 'cookie_ds_demo'
    command: /bin/bash
  shell:
    image: 'cookie_ds_demo'
    working_dir: /app
    # make container wait
    command: tail -F anything
    volumes: 
      - '.:/app'
  rstudio:
    image: 'cookie_ds_demo'
    ports: 
      - '8787:8787'
    volumes: 
      - '.:/home/rstudio/app'
    command: /init
    environment:
      PASSWORD: '123'
      USER: 'rstudio'
  
