version: '3.7'
services:
  build_image:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'cookie_ds_demo'
    command: /bin/bash
    
  build_jup_image:
    build:
      context: .
      dockerfile: docker/jupyter.dockerfile
    image: 'cookie_ds_demo_jupyter'

  shell:
    image: 'cookie_ds_demo'
    working_dir: /app
    # make container wait
    command: tail -F anything
    volumes: 
      - '.:/app'
  rstudio:
    image: 'cookie_ds_demo'
    ports: 
      - '8787:8787'
    volumes: 
      - '.:/home/rstudio/app'
    command: /init
    environment:
      PASSWORD: '123'
      USER: 'rstudio'
  
  jupyter:
    image: 'cookie_ds_demo_jupyter'
    ports:
      - '8888:8888'
    volumes:
      - '.:/home/jovyan/work'
    environment:
      JUPYTER_TOKEN: '123'

  jekyll:
    image: jekyll/jekyll:pages
    ports:
      - '4000:4000'
    volumes:
      - './docs:/srv/jekyll'
    command:
      jekyll serve
